name: Docker Build

on:
  push:
    paths:
    - 'Dockerfile'
    - '**.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jerray/publish-docker-action@master
      with:
        username: metowolf
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: metowolf/nginx
        tags: edge
